# Generated by Django 6.1 on 2026-08-30 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(blank=True, max_length=255)),
                ('drives', models.JSONField(blank=True, default=list)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive', models.CharField(max_length=8)),
                ('path', models.TextField()),
                ('name', models.CharField(max_length=512)),
                ('extension', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.endpointdevice')),
            ],
            options={
                'ordering': ['drive', 'path'],
                'indexes': [models.Index(fields=['drive'], name='core_archiv_drive_fc5bd5_idx'), models.Index(fields=['name'], name='core_archiv_name_971bc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'path'), name='unique_archived_file_per_device')],
            },
        ),
    ]
