# Generated by Django 6.1 on 2026-08-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointdevice',
            name='c_drive_total_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endpointdevice',
            name='c_drive_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endpointdevice',
            name='secondary_total_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endpointdevice',
            name='secondary_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endpointdevice',
            name='storage_status',
            field=models.CharField(default='Optimal', max_length=32),
        ),
    ]
