# Generated by Django 6.1 on 2026-08-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_endpointdevice_c_drive_total_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedfile',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedfile',
            name='content_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='archivedfile',
            name='content_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivedfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='archivedfile',
            name='content_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
