# Generated by Django 6.1 on 2026-08-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_archivedfile_content_archivedfile_content_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointdevice',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='endpointdevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
